# Docker file for image szewaiyuendetermined/environments:offload_1
FROM determinedai/environments:cuda-11.3-pytorch-1.10-deepspeed-0.8.3-gpu-6eceaca
RUN pip install transformers
RUN pip install accelerate