
name: test_grid_new_api
entrypoint: python3 grid_new_api.py
searcher:
  name: grid
  metric: none
  max_length: 100
resources:
  slots_per_trial: 2
  max_slots: 4
max_restarts: 1
environment:
  image: szewaiyuendetermined/environments:offload_1
hyperparameters:
    rank:
      type: int
      minval: 0
      maxval: 1
      count: 2
    num_replica:
      type: const
      val: 2
